#!/usr/bin/env node
/**
 * Turn one translator-facing JSON file into the two catalogs the apps load.
 *
 * A language is written **once**, as `english → translation` covering both
 * apps, and this splits it: the Mac keeps the strings its UI asks for, the
 * phone keeps its own. Writing the two by hand would mean translating the
 * fifteen shared strings twice and letting them drift.
 *
 *   node tools/i18n-gen.mjs <tag> <path-to.json>
 *
 * Writes `src/locales/<tag>.ts` and the Kotlin catalog for the Android app.
 * Entries that match no key in either app are reported and dropped — they are
 * almost always English copy that has since been edited, and shipping them
 * would quietly bloat every catalog with strings nothing can ever look up.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const here = dirname(fileURLToPath(import.meta.url));
const app = join(here, "..");
const androidApp = join(app, "..", "..", "droiddock-android", "app", "src", "main", "java", "com", "droiddock", "app");

const [tag, source] = process.argv.slice(2);
if (!tag || !source) {
  console.error("usage: i18n-gen.mjs <tag> <translations.json>");
  process.exit(2);
}

const macKeys = new Set(
  execFileSync("node", [join(here, "i18n-keys.mjs")], { encoding: "utf8" })
    .split("\n").filter(Boolean).map((l) => JSON.parse(l)),
);
const androidKeys = new Set(
  readFileSync(join(here, "android-keys.txt"), "utf8")
    .split("\n").filter(Boolean).map((l) => JSON.parse(l)),
);

const all = JSON.parse(readFileSync(source, "utf8"));
const unknown = Object.keys(all).filter((k) => !macKeys.has(k) && !androidKeys.has(k));
const missingMac = [...macKeys].filter((k) => !(k in all));
const missingAndroid = [...androidKeys].filter((k) => !(k in all));

const lit = (s) => JSON.stringify(s);
const pick = (keys) =>
  [...keys].filter((k) => k in all && all[k] !== "").sort();

const macEntries = pick(macKeys);
writeFileSync(
  join(app, "src", "locales", `${tag}.ts`),
  `// Generated by tools/i18n-gen.mjs — edit the source translation file, not this.\n` +
    `import type { Catalog } from "../lib/i18n";\n\n` +
    `export const ${tag.replace(/-/g, "_")}: Catalog = {\n` +
    macEntries.map((k) => `  ${lit(k)}: ${lit(all[k])},`).join("\n") +
    `\n};\n`,
);

const androidEntries = pick(androidKeys);
const kt = tag.replace(/-/g, "_");
writeFileSync(
  join(androidApp, `Locale_${kt}.kt`),
  `// Generated by droiddock-tauri/app/tools/i18n-gen.mjs — edit the source\n` +
    `// translation file, not this.\npackage com.droiddock.app\n\n` +
    `val catalog_${kt}: Catalog = mapOf(\n` +
    androidEntries.map((k) => `    ${lit(k)} to ${lit(all[k])},`).join("\n") +
    `\n)\n`,
);

console.log(
  `${tag}: mac ${macEntries.length}/${macKeys.size}, android ${androidEntries.length}/${androidKeys.size}` +
    (unknown.length ? `, ${unknown.length} unknown dropped` : "") +
    (missingMac.length || missingAndroid.length
      ? `, missing ${missingMac.length + missingAndroid.length}`
      : ""),
);
for (const k of unknown.slice(0, 5)) console.log(`  unknown  ${lit(k)}`);
for (const k of [...missingMac, ...missingAndroid].slice(0, 5)) console.log(`  missing  ${lit(k)}`);
